version: '3.8'

services:

  # PostgreSQL
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crackcamp
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis
  redis:
    image: redis:7-alpine
    container_name: redis_server
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # NestJS Backend
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: nest_app
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      PORT: 4000

      REDIS_HOST: redis
      REDIS_PORT: 6379

      DATABASE_URL: postgresql://postgres:postgres@db:5432/crackcamp

      JWT_SECRET: ${JWT_SECRET}

      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}

      GEMINI_API_KEY: ${GEMINI_API_KEY}

      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}

  # React Frontend
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: react_app
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  pgdata:
