services:
  app:
    build: .
    container_name: nest_app
    ports:
      - "4000:4000"
    depends_on:
      - redis
    environment:
      PORT: 4000
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DATABASE_URL: postgresql://postgres:pandiselvi@host.docker.internal:5432/CrackCamp
      JWT_SECRET: ${JWT_SECRET}
      EMAIL_USER: kabilesh0214@gmail.com
      EMAIL_PASS: ${EMAIL_PASS}
    volumes:
      - .:/app
    command: npm run start:dev

  redis:
    image: redis:7
    container_name: redis_server
    ports:
      - "6379:6379"
